### ISSUE TITLE
WISH: insert-event-func to check for dupes

### ISSUE THREAD

**Issue by hiiamboris** [red/REP#117]
This has been discussed but never documented: `insert-event-func` should not add a function that's already in the pipeline.

Currently, one has to *always* write:
```
	unless find/same system/view/handlers :event-func [
		insert-event-func :event-func
	]
```
instead of just
```
insert-event-func :event-func
```

Needless to say, people are also unknowingly falling into the trap of not checking for the duplicates and blowing up the event pipeline.

**Comment by greggirwin** [comment]
If there is no good reason to _allow_ dupe event funcs, and I can't think of one, we should probably consider this a bug rather than a REP. @qtxie @dockimbel what do you think?

**Comment by dockimbel** [comment]
This should not have been a REP, just a normal ticket, as it's just a very simple code improvement.

Implemented: https://github.com/red/red/commit/ae86a8972b23f6dd26af9132f7425e8669daac5d
