### ISSUE TITLE
WISH: caret position in FIELD and AREA faces available to programmer through Red function or facet

### ISSUE THREAD

**Issue by meijeru** [red/REP#123]
Editing in a FIELD or AREA face is done by the user with keyboard and mouse in the usual way. The programmer sees the result on certain events (on-change, on-enter, ...) by inspecting the /text facet, but cannot control the process otherwise. As a minimum to allow some finer control, the position of the caret could be made available.

Currently, the position of the caret is not available to the programmer except by invoking some very low-level functions using routines. This in contrast to the case where the user has selected some substring of the face contents, because then the facet /selected is updated. I see two possibilities: either the caret is shown in /selected as a pair with 0 as second coordinate (this normally indicates the length of the selected substring) or a function is supplied which itself calls the low-level functions.

**Comment by meijeru** [comment]
Closing this, as it is a re-invention of the wheel....

**Comment by hiiamboris** [comment]
duplicate of
https://github.com/red/red/issues/2422
https://github.com/red/red/issues/3194
#5
#76
