### ISSUE TITLE
WISH: Support SKIP refinement for REVERSE

### ISSUE THREAD

**Issue by rebolek** [red/REP#28]
Some `action!`s (i.e. `find`, `sort`, ...) can treat series as fixed size records with `/skip` refinement. It would be useful if `reverse` was one of them, so it would be possible to do:

```
>> reverse/skip [a 1 b 2 c 3] 2
== [c 3 b 2 a 1]
```

**Comment by endo64** [comment]
This looks like a very rare case (I didn't need even once)

Here is the all functions which has `skip` refinement, they all have strong cases:

```
difference
exclude
find
intersect
new-line
select
skip
sort
union
unique
```

OTOH it should be very easy to add such functionality.

**Comment by rebolek** [comment]
It may be rare, but when you need it, you certainly would appreciate it :smile: 
It should be easy to implement and would make actions more consistent.
If I find some time, I may try looking into it and make a merge request.

**Comment by 9214** [comment]
https://github.com/red/red/issues/3004
