### ISSUE TITLE
FIND on any-block! (except hash!) series should allow a typeset! argument

### ISSUE THREAD

**Issue by meijeru** [red/REP#29]
Currently one can find a value in a block by type (e.g. `find [1 "a" 2.0 #"b" 3% 4.5.6 #c] percent!` will give `[3% 4.5.6 #c]`.

It would be nice to be able to find by typeset, e.g. `find ["a" 2.0 'b 4.5.6 c: ] any-word!` would give `['b 4.5.6 c:]`

**Comment by meijeru** [comment]
I have got the following use case: to search for the first argument in a function spec block, one cannot do `find spec any-word!` but must do `any [find spec word! find spec lit-word! find spec get-word!]` which is order dependent: e.g. if the spec starts with a lit-word argument, this will not be found.

**Comment by 9214** [comment]
Should be closed as granted by https://github.com/red/red/commit/f3400414.
