### ISSUE TITLE
WISH: support issue as map key

### ISSUE THREAD

**Issue by hiiamboris** [red/REP#63]
See :point_up: [/help January 23, 2020 9:36 PM](https://gitter.im/red/help?at=5e29e7c0da04a624f46e1a30)

TL;DR: make these work:
```
#( #issue 100 )
put #() #issue 100
select #() #issue
extend #() [#issue 100]
```
No default coercion from issue! to any-word! and back should be done (`m/(#issue) <> m/issue`).

I wouldn't mind if `refinement!` type was supported as well.

**Comment by 9214** [comment]
Granted by https://github.com/red/red/pull/4580. **Edit**: partially.

**Comment by hiiamboris** [comment]
```
>> m: #() ()
>> put m #abc 234
*** Script Error: put does not allow issue for its key argument
*** Where: put
*** Stack:  
```

**Comment by 9214** [comment]
Bloody hell.

**Comment by hiiamboris** [comment]
Works in `Red 0.6.4 for Windows built 4-Apr-2022/15:09:55+03:00  commit #28dad01`
