### ISSUE TITLE
WISH: currency-of reflector for money! values

### ISSUE THREAD

**Issue by meijeru** [red/REP#69]
Operations on `money!` values need to be able to take account of the currency feature. Therefore one needs a reflector, call it `currency-of`. When the currency is indicated on the value, this will yield a `word!` value, else `none`.
```
currency-of USD$1.07 => USD
currency-of $0.00 => none
```

**Comment by meijeru** [comment]
In the light of the continuing discussion on #68, an alternative for my wish would be an _accessor_, call it `/currency`, thus
```
a: USD$1.07
a/currency => USD
```

**Comment by 9214** [comment]
Can be closed.
